const { SlashCommandBuilder } = require('discord.js');
const { AskManager } = require('../utils/models-managers.js');


const ask = new AskManager();

// export an object with the data and execute properties
module.exports = {
    data: new SlashCommandBuilder()
	.setName('ask')
	.setDescription('Send a specific/long answer generated by GPT-3!')
	.addStringOption(option =>
		option.setName('prompt')
			.setDescription('Type your question')
            .setRequired(true)),

    async execute(interaction) {
        // defer reply until the command finishes executing
        await interaction.deferReply();
        // get input option from the interaction object
        const input = interaction.options.getString('prompt');
        // generate answer from prompt
        const output = await ask.generate_answer(input);
        // send the reply with the generated output
        await interaction.editReply(output);
        console.log('Answer sent!');
    }
};
